language: rust
rust:
  - nightly-2018-04-06

install:
- git clone https://github.com/konstin/pyo3
- cd pyo3
- git checkout capybara
- cd ..
- git clone https://github.com/konstin/helix
- cd helix
- git checkout split_out_init
- cd ..
- rustup target add wasm32-unknown-unknown
- mkdir -p "$(rbenv root)"/plugins
- git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build

# Installing the different toolchains

## nvm for node
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash

## pyenv for python
- git clone https://github.com/pyenv/pyenv.git ~/.pyenv
- export PYENV_ROOT="$HOME/.pyenv"
- export PATH="$PYENV_ROOT/bin:$PATH"

## The actual targets
- rustup target add wasm32-unknown-unknown
- rbenv install 2.5.1
- rbenv local 2.5.1
- pyenv install 3.5.5
- pyenv local 3.5.5
- python3 -V
- nvm install 8
- nvm use 8

script:
- ./test.sh
