language: rust
rust:
  - nightly

cache: cargo

install:
  - rustup default nightly-2018-04-06
  - git clone https://github.com/konstin/pyo3
  - cd reusable_codegen
  - git checkout reusable_codegen
  - cd ..
  - git clone https://github.com/konstin/helix
  - cd helix
  - git checkout split_out_init
  - cd ..

script:
  - ./test.sh