[package]
name = "omni"
version = "0.1.0"
authors = ["konstin <konstin@mailbox.org>"]
description = "A framework for generating bindings from Rust to arbitrary languages"
readme = "readme.md"
keywords = ["ffi", "bindings", "pyo3", "python", "helix", "ruby", "rails"]
categories = ["api-bindings", "development-tools::ffi"]
license = "Apache-2.0 OR MIT"

[features]
omni_python = ["omni-derive/omni_python"]
omni_ruby = ["omni-derive/omni_ruby"]

[dependencies]
pyo3 = { path = "pyo3", features = ["extension-module"] }
helix = { path = "helix" }
omni-derive = { path = "omni-derive" }
pyo3cls = { path = "pyo3/pyo3cls" }

[workspace]
members = [
    "omni-derive",
    "tests/fail-test",
    "tests/helix-test",
    "tests/pyo3-test",
    "tests/stub-test",
]

exclude = [
    "helix",
    "pyo3",
]
