[package]
name = "capybara"
version = "0.1.0"
authors = ["konstin <konstin@mailbox.org>"]
description = "A framework for generating bindings from Rust to arbitrary languages"
readme = "readme.md"
keywords = ["ffi", "bindings", "pyo3", "python", "helix", "ruby", "rails"]
categories = ["api-bindings", "development-tools::ffi"]
license = "Apache-2.0 OR MIT"

[features]
capybara_python = ["capybara-derive/capybara_python", "pyo3", "pyo3cls"]
capybara_ruby = ["capybara-derive/capybara_ruby", "helix"]
capybara_wasm = ["capybara-derive/capybara_wasm", "wasm-bindgen"]

[dependencies]
pyo3 = { path = "pyo3", features = ["extension-module"], optional = true }
helix = { path = "helix", optional = true }
capybara-derive = { path = "capybara-derive" }
pyo3cls = { path = "pyo3/pyo3cls", optional = true }
# We need that commit, but hasn't been released yet
wasm-bindgen = { git  = "https://github.com/rustwasm/wasm-bindgen", rev = "9421edaab5fce92cc901a5afa1dc67d0eae15ac7", optional = true }

[workspace]
members = [
    "capybara-derive",
    "syn-0-11",
    "tests/fail-test",
    "tests/helix-test",
    "tests/pyo3-test",
    "tests/stub-test",
    "tests/wasm-test",
]

exclude = [
    "helix",
    "pyo3",
]
