[package]
name = "capybara"
version = "0.1.0"
authors = ["konstin <konstin@mailbox.org>"]
description = "A framework for generating bindings from Rust to arbitrary languages"
readme = "readme.md"
keywords = ["ffi", "bindings", "pyo3", "python", "helix", "ruby", "rails"]
categories = ["api-bindings", "development-tools::ffi"]
license = "Apache-2.0 OR MIT"

[features]
python = ["capybara-derive/python", "pyo3", "pyo3cls"]
ruby = ["capybara-derive/ruby", "helix"]
wasm = ["capybara-derive/wasm", "wasm-bindgen"]

[dependencies]
pyo3 = { path = "pyo3", features = ["extension-module"], optional = true }
helix = { path = "helix", optional = true }
capybara-derive = { path = "capybara-derive" }
pyo3cls = { path = "pyo3/pyo3cls", optional = true }
wasm-bindgen = { version = "0.2.7", optional = true }

[workspace]
members = [
    "capybara-derive",
    "capybara-derive/syn-0-11",
    "capybara-derive/quote-0-3",
    "tests",
    "compare-codegen/*/",
]

exclude = [
    "helix",
    "pyo3",
]
