[package]
name = "compare-codegen-helix"
version = "0.1.0"
authors = ["konstin <konstin@mailbox.org>"]
edition = "2018"

[dependencies]
helix = { git = "https://github.com/konstin/helix", branch = "capybara"  }
