require 'bundler/setup'
import 'lib/tasks/helix_runtime.rake'

task :test => :build do
    require "helix-test"
    class AssertionError < RuntimeError
    end
    def assert &block
	    raise AssertionError unless yield
    end
    x = ExportedClass.add_and_print(21, 21)
    assert { x == 42 }
    y = ExportedClass.new 1337
    assert { y.get_number == 1337 }
end
