#!/usr/bin/env python3

import json
import os
import shlex
import subprocess
from importlib import import_module
from shutil import copyfile


def main():
    subprocess.check_call(shlex.split("cargo build"))

    metadata = json.loads(subprocess.check_output(shlex.split("cargo metadata --format-version 1")))
    python_module_name = metadata["resolve"]["root"].split(" ")[0].replace("-", "_")
    python_so_name = python_module_name + ".so"
    cargo_lib_name = "lib" + python_module_name + ".so"
    path = os.path.join(metadata["target_directory"], "debug", cargo_lib_name)
    copyfile(path, python_so_name)

    my_module = import_module(python_module_name)

    x = my_module.MyClass.add_and_print(21, 21)
    assert x == 42
    assert 42 == my_module.MyClass(42).get_number()

    os.remove(python_so_name)


if __name__ == '__main__':
    main()
