[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "capybara-derive"
version = "0.1.0"

[dependencies]
quote = "0.3"
pyo3 = { path = "../pyo3", features = ["extension-module"], optional = true }
pyo3-derive-backend = { path = "../pyo3/pyo3-derive-backend", optional = true }
helix = { path = "../helix", optional = true }

# pyo3 needs syn 0.11, wasm_bindgen needs syn 0.13, so that's where this ugly trick comes in
syn = {features = ["full"], version = "0.13"}
syn-0-11 = {path = "../syn-0-11", optional = true}

[lib]
proc-macro = true

[features]
capybara_python = ["pyo3", "pyo3-derive-backend", "syn-0-11"]
capybara_ruby = ["helix", "syn-0-11"]
capybara_wasm = []
