[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "capybara-derive"
version = "0.1.0"

[dependencies]
quote = "0.5"
pyo3 = { path = "../../pyo3", features = ["extension-module"], optional = true }
pyo3-derive-backend = { path = "../../pyo3/pyo3-derive-backend", optional = true }
helix = { path = "../helix", optional = true }
wasm-bindgen-backend = { version = "=0.2.10", optional = true }

syn = {features = ["full", "extra-traits", "visit-mut"], version = "0.13"}
proc-macro2 = { version = "0.4", features = ["nightly"] }

[lib]
proc-macro = true

[features]
python = ["pyo3", "pyo3-derive-backend"]
ruby = ["helix"]
wasm = ["wasm-bindgen-backend"]
