[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "capybara-derive"
version = "0.1.0"

[dependencies]
quote = "0.5"
pyo3 = { path = "../pyo3", features = ["extension-module"], optional = true }
pyo3-derive-backend = { path = "../pyo3/pyo3-derive-backend", optional = true }
helix = { path = "../helix", optional = true }
wasm-bindgen = { version = "0.2.7", optional = true }
wasm-bindgen-backend = { version = "0.2.7", optional = true }

# pyo3 needs syn 0.11, wasm_bindgen needs syn 0.13, so that's where this ugly trick comes in
syn-0-11 = {path = "syn-0-11", optional = true}
quote-0-3 = {path = "quote-0-3", optional = true}
syn = {features = ["full", "extra-traits", "visit-mut"], version = "0.13"}
proc-macro2 = { version = "0.3", features = ["nightly"] }

[lib]
proc-macro = true

[features]
python = ["pyo3", "pyo3-derive-backend", "syn-0-11", "quote-0-3"]
ruby = ["helix"]
wasm = ["wasm-bindgen", "wasm-bindgen-backend"]
